/**
 * Opportunity Finder - Main JavaScript
 */

// Initialize application
document.addEventListener('DOMContentLoaded', () => {
  initNavigation();
  initMobileMenu();
  initScrollAnimations();
  initPricingToggle();
});

// Navigation scroll effect
function initNavigation() {
  const navbar = DOM.$('.navbar');
  if (!navbar) return;

  let lastScroll = 0;

  window.addEventListener('scroll', () => {
    const currentScroll = window.pageYOffset;

    // Add shadow on scroll
    if (currentScroll > 10) {
      navbar.style.boxShadow = 'var(--shadow-md)';
    } else {
      navbar.style.boxShadow = 'none';
    }

    lastScroll = currentScroll;
  });
}

// Mobile menu toggle
function initMobileMenu() {
  const menuToggle = DOM.$('[data-action="toggle-menu"]');
  const mobileMenu = DOM.$('.mobile-menu');

  if (menuToggle && mobileMenu) {
    menuToggle.addEventListener('click', () => {
      mobileMenu.classList.toggle('active');
      menuToggle.classList.toggle('active');
    });
  }
}

// Scroll animations
function initScrollAnimations() {
  const animatedElements = DOM.$$('[data-animate]');

  if (animatedElements.length === 0) return;

  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const animation = entry.target.dataset.animate;
        entry.target.classList.add(animation);
        observer.unobserve(entry.target);
      }
    });
  }, {
    threshold: 0.1,
    rootMargin: '0px 0px -50px 0px'
  });

  animatedElements.forEach(el => observer.observe(el));
}

// Pricing toggle (monthly/yearly)
function initPricingToggle() {
  const toggle = DOM.$('[data-pricing-toggle]');
  const prices = DOM.$$('[data-price]');

  if (!toggle || prices.length === 0) return;

  toggle.addEventListener('change', () => {
    const isYearly = toggle.checked;

    prices.forEach(priceEl => {
      const monthlyPrice = priceEl.dataset.priceMonthly;
      const yearlyPrice = priceEl.dataset.priceYearly;

      if (monthlyPrice && yearlyPrice) {
        priceEl.textContent = isYearly ? yearlyPrice : monthlyPrice;
      }
    });
  });
}

// Smooth scroll to element
function scrollToElement(selector, offset = 80) {
  const element = DOM.$(selector);
  if (element) {
    const top = element.getBoundingClientRect().top + window.pageYOffset - offset;
    window.scrollTo({ top, behavior: 'smooth' });
  }
}

// Copy to clipboard
async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    Toast.success('Copied to clipboard!');
    return true;
  } catch (err) {
    Toast.error('Failed to copy');
    return false;
  }
}

// Share functionality
function shareOpportunity(opportunity) {
  const title = opportunity.name || opportunity.idea || opportunity.userIdea || "Idée business";
  const text = `
${title}

Problème :
${opportunity.problem || "Non disponible"}

Idée :
${opportunity.idea || opportunity.userIdea || "Non disponible"}

Score :
${opportunity.scores?.opportunity ?? "-"} / 100

Généré avec Opportunity Finder
`;

  if (navigator.share) {
    navigator.share({
      title,
      text,
      url: window.location.href
    });
  } else {
    copyToClipboard(text);
  }
}

// Export opportunity as text
function exportAsText(opportunity) {
  const title = opportunity.name || opportunity.idea || opportunity.userIdea || "idee-business";

  const text = `
OPPORTUNITY FINDER - ANALYSE BUSINESS
=====================================

Nom :
${opportunity.name || "Non disponible"}

Slogan :
${opportunity.slogan || "Non disponible"}

Type :
${opportunity.businessType || "Business"}

Problème :
${opportunity.problem || "Non disponible"}

Idée :
${opportunity.idea || opportunity.userIdea || "Non disponible"}

Cible :
${Array.isArray(opportunity.targetUsers) ? opportunity.targetUsers.join(", ") : opportunity.targetUsers || "Non disponible"}

Monétisation :
${opportunity.monetization || opportunity.pricing || "Non disponible"}

Score :
${opportunity.scores?.opportunity ?? "-"} / 100

Demande :
${opportunity.scores?.demand ?? "-"} / 100

Concurrence :
${opportunity.scores?.competition ?? "-"} / 100

Generated by Opportunity Finder
`;

  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.toLowerCase().replace(/\s+/g, "-")}.txt`;

  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  URL.revokeObjectURL(url);

  Toast.success("Analyse exportée avec succès");
}

// Generate simple PDF (text-based)
function generatePDF(opportunity) {
  // For a real implementation, you'd use a library like jsPDF
  // For now, we'll export as formatted text
  exportAsText(opportunity);
}

// Format currency
function formatCurrency(amount, currency = 'EUR') {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency
  }).format(amount);
}

// Debounce function
function debounce(func, wait) {
  let timeout;
  return function executedFunction(...args) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
}

// Throttle function
function throttle(func, limit) {
  let inThrottle;
  return function(...args) {
    if (!inThrottle) {
      func.apply(this, args);
      inThrottle = true;
      setTimeout(() => inThrottle = false, limit);
    }
  };
}

// Page-specific initialization
const PageInit = {
  // Landing page
  landing() {
    // Animate hero elements
    const heroElements = DOM.$$('.hero-content > *');
    heroElements.forEach((el, i) => {
      el.style.opacity = '0';
      el.style.transform = 'translateY(20px)';
      setTimeout(() => {
        el.style.transition = 'all 0.5s ease';
        el.style.opacity = '1';
        el.style.transform = 'translateY(0)';
      }, 100 * i);
    });
  },

  // Dashboard page
  async dashboard() {
  if (!Auth.requireAuth()) return;
  await initDashboard();
},

  // Profile page
  profile() {
    if (!Auth.Auth()) return;
    initProfile();
  },

  // Login page
  login() {
    Auth.redirectIfAuth();
  },

  // Signup page
  signup() {
    Auth.redirectIfAuth();
  }
};

const userMenuTrigger = document.getElementById("userMenuTrigger");
const userDropdown = document.getElementById("userDropdown");

if (userMenuTrigger && userDropdown) {
  userMenuTrigger.addEventListener("click", (e) => {
    e.stopPropagation();
    userDropdown.classList.toggle("open");
  });

  document.addEventListener("click", () => {
    userDropdown.classList.remove("open");
  });
}

// Initialize page-specific functionality
function initPage() {
  const page = document.body.dataset.page;
  if (page && PageInit[page]) {
    PageInit[page]();
  }
}

// Mark as bound so auth.js doesn't double-bind on pages that load main.js
window.__userMenuBound = true;

document.addEventListener("click", (e) => {
  const toggle = e.target.closest(".user-menu-toggle");
  const menu   = e.target.closest(".user-menu");

  document.querySelectorAll(".user-menu").forEach(item => {
    if (item !== menu) item.classList.remove("open");
  });

  if (toggle && menu) {
    e.stopPropagation();
    menu.classList.toggle("open");
  } else if (!menu) {
    document.querySelectorAll(".user-menu").forEach(item => item.classList.remove("open"));
  }
});

document.addEventListener("DOMContentLoaded", () => {
  if (document.body.dataset.page === "profile") {
    initProfilePage();
  }
});

function initProfilePage() {
  const user = Auth.getUser();

  if (!user) {
    window.location.href = "login.html";
    return;
  }

  const avatar = document.getElementById("profileAvatar");
  const name = document.getElementById("profileName");
  const email = document.getElementById("profileEmail");
  const plan = document.getElementById("profilePlan");
  const editName = document.getElementById("editName");
  const editEmail = document.getElementById("editEmail");

  if (avatar) avatar.textContent = user.name.charAt(0).toUpperCase();
  if (name) name.textContent = user.name;
  if (email) email.textContent = user.email;
  if (plan) plan.textContent = user.plan.toUpperCase();
  if (editName) editName.value = user.name;
  if (editEmail) editEmail.value = user.email;
}

// Run page initialization
// document.addEventListener('DOMContentLoaded', initPage);
